import { NextResponse } from "next/server"

export async function POST(request: Request) {
  try {
    const { data, reportType } = await request.json()

    // Generate HTML content for the PDF
    const htmlContent = generateReportHTML(data, reportType)

    // In a real implementation, you would use a library like Puppeteer or jsPDF
    // For this demo, we'll create a simple HTML-based report that can be printed as PDF
    const reportId = `report_${Date.now()}`
    const filename = `${data.title?.replace(/\s+/g, "_") || "project"}_report_${reportId}.html`

    // Create a blob URL for the HTML content
    const blob = new Blob([htmlContent], { type: "text/html" })

    // In a real app, you'd save this to a file system or cloud storage
    // For demo purposes, we'll return the HTML content as a data URL
    const dataUrl = `data:text/html;base64,${Buffer.from(htmlContent).toString("base64")}`

    return NextResponse.json({
      url: dataUrl,
      filename: filename,
      success: true,
    })
  } catch (error) {
    console.error("Report generation error:", error)
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 })
  }
}

function generateReportHTML(data: any, reportType: string): string {
  const currentDate = new Date().toLocaleDateString()

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A3E Environmental Report</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: white;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #059669;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #059669;
            margin-bottom: 10px;
        }
        .report-title {
            font-size: 28px;
            color: #1f2937;
            margin: 20px 0;
        }
        .section {
            margin: 25px 0;
            padding: 20px;
            border-left: 4px solid #059669;
            background: #f9fafb;
        }
        .section h3 {
            color: #059669;
            margin-top: 0;
        }
        .data-grid {
            display: grid;
            grid-template-columns: 1fr 2fr;
            gap: 10px;
            margin: 15px 0;
        }
        .data-label {
            font-weight: bold;
            color: #374151;
        }
        .data-value {
            color: #6b7280;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            color: #6b7280;
            font-size: 14px;
        }
        @media print {
            body { margin: 0; padding: 15px; }
            .section { break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">A3E Environmental Consultants</div>
        <div class="report-title">Project Analysis Report</div>
        <div>Generated on ${currentDate}</div>
    </div>

    <div class="section">
        <h3>Project Overview</h3>
        <div class="data-grid">
            <div class="data-label">Project Title:</div>
            <div class="data-value">${data.title || "N/A"}</div>
            <div class="data-label">Category:</div>
            <div class="data-value">${data.category || "N/A"}</div>
            <div class="data-label">Budget:</div>
            <div class="data-value">$${Number(data.budget || 0).toLocaleString()}</div>
            <div class="data-label">Duration:</div>
            <div class="data-value">${data.duration || "N/A"}</div>
        </div>
    </div>

    ${
      data.details
        ? `
    <div class="section">
        <h3>Project Details</h3>
        <p>${data.details}</p>
    </div>
    `
        : ""
    }

    ${
      data.impactScore
        ? `
    <div class="section">
        <h3>Cost-Benefit Analysis</h3>
        <div class="data-grid">
            <div class="data-label">Impact Score:</div>
            <div class="data-value">${data.impactScore}</div>
            <div class="data-label">Risk Factor:</div>
            <div class="data-value">${data.riskFactor}</div>
            <div class="data-label">Recommendation:</div>
            <div class="data-value">${data.recommendation}</div>
        </div>
    </div>
    `
        : ""
    }

    <div class="section">
        <h3>Report Summary</h3>
        <p>This report was generated by the Iris AI system using the ${reportType} template. 
        The analysis includes comprehensive project data and recommendations based on current 
        environmental consulting best practices.</p>
    </div>

    <div class="footer">
        <p>A3 Environmental Consultants | Professional Environmental Services Since 2009</p>
        <p>This report was generated automatically by Iris AI System</p>
    </div>
</body>
</html>
  `
}
