import { NextResponse } from "next/server"

export async function POST(request: Request) {
  try {
    const { inspectionId, framework, findings } = await request.json()

    // Generate compliance document HTML
    const htmlContent = generateComplianceHTML(inspectionId, framework, findings)
    const filename = `${framework}_Compliance_${inspectionId}.html`

    // Create data URL for download
    const dataUrl = `data:text/html;base64,${Buffer.from(htmlContent).toString("base64")}`

    return NextResponse.json({
      id: `DOC-${Date.now()}`,
      url: dataUrl,
      filename,
      success: true,
    })
  } catch (error) {
    console.error("Compliance document generation error:", error)
    return NextResponse.json({ error: "Failed to generate compliance document" }, { status: 500 })
  }
}

function generateComplianceHTML(inspectionId: string, framework: string, findings: any[]): string {
  const currentDate = new Date().toLocaleDateString()

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${framework} Compliance Report - ${inspectionId}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; border-bottom: 3px solid #059669; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #059669; margin-bottom: 10px; }
        .section { margin: 25px 0; padding: 20px; border-left: 4px solid #059669; background: #f9fafb; }
        .finding { margin: 15px 0; padding: 15px; border: 1px solid #e5e7eb; border-radius: 8px; }
        .high-risk { border-left: 4px solid #dc2626; background: #fef2f2; }
        .medium-risk { border-left: 4px solid #d97706; background: #fffbeb; }
        .low-risk { border-left: 4px solid #059669; background: #f0fdf4; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">A3 Environmental Consultants</div>
        <h1>${framework} Environmental Compliance Report</h1>
        <p>Inspection ID: ${inspectionId}</p>
        <p>Generated: ${currentDate}</p>
    </div>

    <div class="section">
        <h3>Executive Summary</h3>
        <p>This ${framework} compliance report documents environmental findings from field inspection ${inspectionId}. 
        A total of ${findings.length} environmental concerns were identified and assessed.</p>
    </div>

    <div class="section">
        <h3>Environmental Findings</h3>
        ${
          findings.length === 0
            ? "<p>No environmental concerns identified during this inspection.</p>"
            : findings
                .map(
                  (finding) => `
        <div class="finding ${finding.severity.toLowerCase()}-risk">
            <h4>${finding.type.toUpperCase()} - ${finding.severity} Risk</h4>
            <p><strong>Location:</strong> ${finding.location}</p>
            <p><strong>Description:</strong> ${finding.description}</p>
            <p><strong>Detected:</strong> ${new Date(finding.timestamp).toLocaleString()}</p>
        </div>
        `,
                )
                .join("")
        }
    </div>

    <div class="section">
        <h3>Regulatory Compliance</h3>
        <p>This inspection was conducted in accordance with ${framework} guidelines and standards. 
        All findings have been documented with appropriate chain of custody procedures.</p>
        <p>Recommended next steps include detailed sampling and analysis for any high-risk findings identified.</p>
    </div>

    <div class="footer">
        <p>A3 Environmental Consultants | Professional Environmental Services Since 2009</p>
        <p>Generated by IRIS AI Field Inspection System</p>
    </div>
</body>
</html>
  `
}
